board/urls.py
from django.urls import path
from . import views

app_name = 'board'

urlpatterns = [
    # 글목록
    path('postlist/', views.postlist, name='postlist'),
     
    # 글 페이지
    path('post/<int:post_no>/', views.post, name='post'),
    
    
    # 글 crud
   
    path('post/write/', views.write, name='write'),
    path('post/post/', views.post, name='post'),
    path('post/<int:post_no>/update/',views.update, name="post_update"),
    path('post/<int:post_no>/delete/',views.delete, name="post_delete"),
    # path('post/<int:post_no>/download/',views.download, name="post_file_download"),
    
    # 댓글
    path('post/<int:post_no>/comment_write/',views.comment_write, name="comment_write"),
    # path('post/<int:post_no>/comment_delete/<int:comment_no>',views.comment_delete, name="comment_delete"),
    
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from config import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('main.urls')),
    path('dobby/', include('dobby.urls')),
    path('board/', include('board.urls')),
]+ static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

dobby/urls.py
from django.urls import path
from . import views

app_name = 'dobby'

urlpatterns = [
    path('edit/', views.edit, name='edit'),      
    path('result/', views.result, name='result'),
    path('result_thumb/', views.result_thumb, name='result_thumb'), 
    path('title_select/', views.title_select, name='title_select'),     
    path('fun/', views.fun, name='fun'),
    path('result/download/', views.download, name='dobbydown'),
    # path('')    
]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('main/', views.main, name='main'),    
    path('signup/', views.signup, name='signup'),    
    path('login/', views.login, name='login'),    
    path('logout/', views.logout, name='logout'),  
    path('my/', views.my, name='my'),   
    # path('activate/<str:uidb64>/<str:token>', views.Activate.as_view(), name='status'), 
]

dobby/models.py
from django.db import models

from main.models import Member

# Create your models here.
class File(models.Model):
    file_no = models.IntegerField(primary_key= True)
    member_id = models.ForeignKey(Member, on_delete=models.CASCADE, db_column='member_id')
    file_name = models.CharField(max_length=50)
    file_date = models.CharField(max_length=1000)
    file_root = models.FileField()
    
    class Meta:
        db_table = 'file'
        app_label = 'dobby'
        unique_together = (('file_no', 'member_id'),)
        managed = False
        
        
class Inputfile(models.Model):
    # input_name = models.CharField(max_length=255)
    input_file = models.FileField()
    # def __str__(self):
    #     return self.input_name

dobby/views.py
import datetime
from glob import glob
import json

import os

from django.shortcuts import redirect, render
from django.http import HttpResponse
import urllib.parse

from matplotlib.image import thumbnail
from config import settings
from config.settings import BASE_DIR, MEDIA_ROOT
from dobby.fu_filter import combine_audio2, filter_srt, total_filter
from dobby.subtitle import combine_audio, subtitle_fps, subtitle_generator
from dobby.summ.demo import demo, demo_title
from dobby.summ.feature_extract import extract_features, save_img, shot_segmentation
from dobby.summ.thumbnail_rcmmnd import rcmd_th
from dobby.imgcap.img_cap import rcmmnd_title, translate_text

from main.models import Member
from .models import File

# Create your views here.
def edit(request):
    s_id = request.session.get('s_id') # session id 유무 체크
    if s_id==None:
        return redirect("/main/login/")
    
    if request.method == "POST":
        upload_file = request.FILES.get('e_file')
        name = upload_file.name 
        request.session['file_name'] = name
        with open(MEDIA_ROOT+'/'+name, 'wb') as file: 
            for chunk in upload_file.chunks():
                file.write(chunk)

    else:
        return render(request, "dobby/edit.html")
    
    # return render(request, "dobby/fun.html", {"upload_file": upload_file})
    return redirect("/dobby/fun/")


def result(request):
    s_id = request.session.get('s_id') # session id 유무 체크
    if s_id==None:
        return redirect("/main/login/")
    

    return render(request, 'dobby/result.html')



def download(request):

    # 다운로드 문제 - db에서 경로로 비교하여 파일탐색 따라서 같은파일이 2번 들어오면 오류 발생
    #              - 같은파일이 존재할 시 구분해서 저장할 필요 있음
    if request.method == 'POST':
        fn = request.POST["filename"]
        filename = File.objects.get(file_root = fn)
        filepath = str(settings.BASE_DIR) + ('%s' % filename.file_root)
        fn = urllib.parse.quote(fn.encode('utf-8'))
        with open(filepath, 'rb') as f:
            response = HttpResponse(f, content_type='application/octet-stream')
            response['Content-Disposition'] = 'attachment; filename*=UTF-8\'\'%s' % fn
    return response




def fun(request):
    s_id = request.session.get('s_id') # session id 유무 체크
    if s_id==None:
        return redirect("/main/login/")

    global fontnum
    global font_col_num
    global font_bg_num
    # return render(request,"dobby/fun.html")
    if request.method == "GET":
      
        return render(request,"dobby/fun.html")
        
    elif 'create' in request.POST:
        txt_pth = MEDIA_ROOT + "\\"+ "subtitle.txt"
        video_pth = MEDIA_ROOT + "\\" + request.session['file_name']
    
        font =  request.POST['font']
        if font == "font1":
            fontnum = 1

        elif font == "font2":
            fontnum = 2

        elif font == "font3":
            fontnum = 3

        fontcolor =  request.POST['fontcolor']
        if fontcolor == "font-color1":
            font_col_num = 1

        elif fontcolor == "font-color2":
            font_col_num = 2

        elif fontcolor == "font-color3":
            font_col_num = 3


        font_bg_num = 0
        bgcolor =  request.POST['bgcolor']
        if bgcolor == "bg-color1":
            font_bg_num = 1

        elif bgcolor == "bg-color2":
            font_bg_num = 2

        elif bgcolor == "bg-color3":
            font_bg_num = 3
        
        subtitle_fps(txt_pth,video_pth)
        subtitle_generator(txt_pth,video_pth,fontnum,font_col_num,font_bg_num)
        combine_audio(video_pth, request.session['file_name'])
        
        
        file_path = str(settings.BASE_DIR) + ('/media/%s' % request.session['file_name'])
        rmv1 = str(settings.BASE_DIR) + ('/media/%s' % 'no_voice.mp4')
        # rmv2 = str(settings.BASE_DIR) + ('/media/%s' % 'subtitle.txt')
        os.remove(file_path)
        os.remove(rmv1)
        # os.remove(rmv2)
        
        now = datetime.datetime.now()
        
        file = File(
            file_name = request.session['file_name'],
            member_id = Member.objects.get(member_id=request.session.get('s_id')),
            file_root = "\\media\\subtitle\\" + request.session['file_name'],
            file_date = now,
        )
        file.save()
        context={
            'file':file
        }
    
    elif 'filter' in request.POST:
        txt_pth = MEDIA_ROOT + "\\"+ "result.txt"  # 필터링 음성추출파일 
        video_pth = MEDIA_ROOT + "\\" + request.session['file_name']
 
        
        filter_srt(txt_pth,video_pth)
        total_filter(txt_pth,video_pth)
        
        audio_pth =  MEDIA_ROOT + "\\" + "filter_audio.mp3"
        combine_audio2(audio_pth,video_pth,request.session['file_name'])
        
        now = datetime.datetime.now()
        
        file = File(
            file_name = request.session['file_name'],
            member_id = Member.objects.get(member_id=request.session.get('s_id')),
            file_root = "\\media\\filter\\" + request.session['file_name'],
            file_date = now,
        )
        file.save()
        context={
            'file':file
        }
    
    elif 'shorts' in request.POST: 
        video_name = request.session['file_name']
        video_root = "\\media\\summary\\" + request.session['file_name']
        duration = "./dobby/summ/data/"+"shots_durations.npy"
        rate = request.POST.get("ratio")
        
        tmp = "./media/"+video_name
        img_dir = "./dobby/summ/tmp/"
        
        # 테스트코드
        # video_name = "20220504_120048.mp4"
        # video_root = "\\media\\summary\\" + "20220504_120048.mp4"
        # duration = "./dobby/summ/data/"+"shots_durations.npy"
        # rate = request.POST.get("ratio")
        
        # tmp = "./media/"+video_name
        # img_dir = "./dobby/summ/tmp/"
        
        
        # 20220504_120048.mp4
        
        
        shot_segmentation(tmp)
        save_img(tmp, duration)
        extract_features(img_dir)
        
        
        print(rate)
        demo(video_name, rate)
        
        now = datetime.datetime.now()
        
        file = File(
            file_name = request.session['file_name'],
            member_id = Member.objects.get(member_id=request.session.get('s_id')),
            file_root = "\\media\\summary\\" + request.session['file_name'],
            file_date = now,
        )
        file.save()
        context={
            'file':file
        }
        
    
    elif 'title' in request.POST:
        video_name = request.session['file_name']
        duration = "./dobby/summ/data/"+"shots_durations.npy"
        
        tmp = "./media/"+video_name
        img_dir = BASE_DIR + "\\dobby\\summ\\tmp\\"
        
        shot_segmentation(tmp)
        save_img(tmp, duration)
        extract_features(img_dir)
        
        representative_points = demo_title(video_name, 0.5)
        imgs = rcmd_th(representative_points, img_dir)
        
        
        context={
            'imgs':imgs
        }
        
        # return render(request, 'dobby/result_thumb_title.html', context)
        return redirect("/dobby/result_thumb/")

    
    
    
    

    return render(request, 'dobby/result.html', context)



def result_thumb(request):
    s_id = request.session.get('s_id') # session id 유무 체크
    if s_id==None:
        return redirect("/main/login/")
    
    if request.method == 'POST':
        img_path = request.POST['thumbnail']
        img='.'+img_path[21:]
        img_file = img_path
        print('******'+img)
        
        
        
        
        key_list =translate_text(rcmmnd_title(img))
        context={
            'img':img,
            'key_list':key_list,
            'img_file':img_file
        }
        return render(request,'dobby/title_select.html', context)
    
    
    
    img_files = []
    k=0
    for file in sorted(glob(MEDIA_ROOT + "\\thumbnail\\"+ "*.jpg")):
        img_files.append(file)
        print(img_files[k])
        print(k,'###$#$#$$')
        k=k+1
        
    context={
        'imgs':img_files,
    }
    
    contJson = json.dumps(context)

    return render(request, 'dobby/result_thumb_title.html', {'contJson':contJson})


def title_select(request):
    
    return render(request, 'dobby/title_select.html')
   

dobby/templates/dobby/edit.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit</title>
    <link rel="stylesheet" href="{% static 'css/edit.css' %}">
    <link rel="stylesheet" href="{% static 'css/topnavi.css' %}">

    <style>
        #modal.modal-overlay {
            width: 100%;
            height: 100%;
            position: absolute;
            left: 0;
            top: 0;
            display: none;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            background: rgba(255, 255, 255, 0.25);
            box-shadow: 0 8px 32px 0 rgba(31, 38, 135, 0.37);
            backdrop-filter: blur(1.5px);
            -webkit-backdrop-filter: blur(1.5px);
            border-radius: 10px;
            border: 1px solid rgba(255, 255, 255, 0.18);
        }
        #modal .modal-window {
            background: rgba( 69, 139, 197, 0.70 );
            box-shadow: 0 8px 32px 0 rgba( 31, 38, 135, 0.37 );
            backdrop-filter: blur( 13.5px );
            -webkit-backdrop-filter: blur( 13.5px );
            border-radius: 10px;
            border: 1px solid rgba( 255, 255, 255, 0.18 );
            width: 1400px;
            height: 500px;
            position: relative;
            top: -100px;
            padding: 10px;
        }
        #modal .title {
            padding-left: 10px;
            display: inline;
            text-shadow: 1px 1px 2px gray;
            color: white;
            
        }
        #modal .title h2 {
            display: inline;
        }
        #modal .close-area {
            display: inline;
            float: right;
            padding-right: 10px;
            cursor: pointer;
            text-shadow: 1px 1px 2px gray;
            color: white;
        }
        
        #modal .content {
            margin-top: 20px;
            padding: 0px 10px;
            text-shadow: 1px 1px 2px gray;
            color: white;
        }
    </style>
</head>

<body>
    <div class='maindobby'>
        <div class="nv">
            <div class="navleft">
                <h1>
                    <a href="{%url 'main:main' %}"><img src="/static/assets/final_logo.png"style="width:100px; height:100px;"></a>
                </h1>
            </div>
            <div class="gnb">
                    <a href="{%url 'main:main' %}" data-link="Home"></a>
                    <a href="{%url 'dobby:edit' %}" data-link="영상편집"></a>
                    <a href="{%url 'board:postlist' %}" data-link="커뮤니티"></a>
            </div>
        </div>
        <div class="title">
            <h1>
                영상을 편집해서 도비를 해방시켜주세요!
            </h1>
        </div>
    </div>


    <div class="content">
        <div class="upload-button">
            <div class="row2">   
                {% comment %} if문: 동영상없으면 input form {% endcomment %}
                <div class="filebox">
                    <label for="input-file">
                        <strong>동영상을 넣어주세요</strong>
                    </label> 
                    <form id="send" action="{% url 'dobby:edit' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <input type="file" id="input-file" name="e_file" style="display:none;">
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class='fun'>
        <input type="submit" id="submit" form="send" value="편집시작!">
    </div>
    <div class="foot">
        <div class="footleft">
            <h1>
                <strong>DOBBYEDIT</strong>
            </h1>
        </div>
        <div class="footright">
            <div class='copyright'>
                <h4>
                    <strong>Contact webmaster for more information. 010-지기지기-기용기용</strong>
                </h4>
            </div>
            <button class="footbtn1" onclick="location.href='{%url 'main:main' %}'">
            </button>
            <button class="footbtn2" onclick="location.href='{%url 'main:main' %}'">
            </button>
        </div>
    </div>  
</body>
<script>
    /*const loremIpsum = document.getElementById("lorem-ipsum")
    fetch("https://baconipsum.com/api/?type=all-meat&paras=200&format=html")
        .then(response => response.text())
        .then(result => loremIpsum.innerHTML = result)*/
    const modal = document.getElementById("modal")
    function modalOn() {
        modal.style.display = "flex"
    }
    function isModalOn() {
        return modal.style.display === "flex"
    }
    function modalOff() {
        modal.style.display = "none"
    }
    const btnModal = document.getElementById("btn-modal")
    btnModal.addEventListener("click", e => {
        modalOn()
    })
    const closeBtn = modal.querySelector(".close-area")
    closeBtn.addEventListener("click", e => {
        modalOff()
    })
    modal.addEventListener("click", e => {
        const evTarget = e.target
        if(evTarget.classList.contains("modal-overlay")) {
            modalOff()
        }
    })
    window.addEventListener("keyup", e => {
        if(isModalOn() && e.key === "Escape") {
            modalOff()
        }
    })
</script>
</html>

dobby/templates/dobby/result.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'css/main.css' %}">
<link rel="stylesheet" href="{% static 'css/result.css' %}">
<link rel="stylesheet" href="{% static 'css/topnavi.css' %}">
 
 
<body>
<div class='maindobby'>
    <div class="nv">
        <div class="navleft">
            <h1>
                <a href="{%url 'main:main' %}"><img src="/static/assets/final_logo.png"style="width:100px; height:100px;"></a>
            </h1>
        </div>
        <div class="gnb">
                <a href="{%url 'main:main' %}" data-link="Home"></a>
                <a href="{%url 'dobby:edit' %}" data-link="영상편집"></a>
                <a href="{%url 'board:postlist' %}" data-link="커뮤니티"></a>
        </div>
    </div>
</div>
 
 
 
<div class="content">
    {%if file %}
    {% comment %} <h3>"{{ file.file_root }}"</h3> {% endcomment %}
    <video class="video" controls poster="//bit.ly/3688dKw">
        <source src="{{ file.file_root }}" type="video/mp4">
        <strong>이 문장은 사용자의 웹 브라우저가 video 태그를 지원하지 않을 때 나타납니다!</strong>
    </video>
    {%else%}
    {% comment %} <h3>sd</h3> {% endcomment %}
    <video class="video" controls poster="//bit.ly/3688dKw">
        <source src="\media\subtitle\media.mp4" type="video/mp4">
        <strong>이 문장은 사용자의 웹 브라우저가 video 태그를 지원하지 않을 때 나타납니다!</strong>
    </video>
    {%endif%}
</div>
<div class="container" style="color:black;" >
    <div>
        <strong>혹시 마음에 안드시나요?<br>그러면 요청주세요. 빠르게 개선해보겠습니다.</strong>
    </div>
</div>

<div class="down_btn" >
    <form action="{% url 'dobby:dobbydown' %}" name="download" method="post">
        {% csrf_token %}
        <input type="hidden" name="filename" value="{{file.file_root}}">
        <a><button type="submit"><img src="/static/assets/download.png"></button></a>
    </form>
</div>
 
 
 
<div class="foot">
    <div class="footleft">
        <h1>
            <strong>DOBBYEDIT</strong>
        </h1>
    </div>
    <div class="footright">
        <div class='copyright'>
            <h4>
                <strong>Contact webmaster for more information. 010-지기지기-기용기용</strong>
            </h4>
        </div>
        <button class="footbtn1" onclick="location.href='{%url 'main:main' %}'">
        </button>
        <button class="footbtn2" onclick="location.href='{%url 'main:main' %}'">
        </button>
    </div>
</div>
 
</body>

dobby/templates/dobby/title_select.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'css/main.css' %}">
<link rel="stylesheet" href="{% static 'css/result.css' %}">
<link rel="stylesheet" href="{% static 'css/topnavi.css' %}">
 
 
<body>
   
<style>
.maindobby{
        position: relative;
        display: flex;
        justify-content: center;
        width: 100%;
        height: 700px;
        background-image: url("/static/assets/lu.png");
        background-size: 100% 100%;
        background-repeat: no-repeat;
        background-position: center center;
    }    
 
.content{
    font-size: 30px;
    padding-left: 3%;
    padding-bottom: 50px;
   
}

/* 수정부분 */
.container{
    font-size: 40px;
    color: rgb(160, 158, 155);
    text-align:center;
    margin-top:100px;
}

.row-2 {
    display: flex;
    justify-content: center;
}
/**/



.row{
    float:right;
    margin:10px 10px 30px 10px;
}

.col-auto{
    height:50px;
}
button{
    height:50px;
    width:100px;
    margin:0px;
}
.foot{
    background-color: rgb(110, 80, 41);
    position: relative;
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 50px 3%;
    top: 100px;
    width: 100%;
    height: 100px;
}
 
.foot h1, h4{
    text-decoration: none;
    color: white;
}
 
.footleft{
    display: flex;
    justify-content: left;
}
 
.footright{
    display: flex;
    justify-content: right;
    align-items: center;
}
 
.footbtn1{
    background-color: rgb(110, 80, 41);
    border-style: none;
    height: 5vh;
    width: 5vw;
    background-image: url("/static/assets/youtube.png");
    background-size: contain;
    background-repeat: no-repeat;
    background-position: center center;
}
 
.footbtn2{
    background-color: rgb(110, 80, 41);
    border-style: none;
    height: 5vh;
    width: 5vw;
    background-image: url("/static/assets/github.jpg");
    background-size: contain;
    background-repeat: no-repeat;
    background-position: center center;
}
p{
    margin:25px 300px 0px 0px;
    font-size:20px;
}
body{
   
    background-color: burlywood;
}
video {
    display: block;
    max-width: 50%;
    margin: 10px auto;
  }


</style>
 
 
<div class='maindobby'>
    <div class="nv">
        <div class="navleft">
            <h1>
                <a href="{%url 'main:main' %}"><img src="/static/assets/final_logo.png"style="width:100px; height:100px;"></a>
            </h1>
        </div>
        <div class="gnb">
                <a href="{%url 'main:main' %}" data-link="Home"></a>
                <a href="{%url 'dobby:edit' %}" data-link="영상편집"></a>
                <a href="{%url 'board:postlist' %}" data-link="커뮤니티"></a>
        </div>
    </div>
</div>
 
 
 
<div class="container" style="color:black;" >
    <div class=row-1>
        <strong>제목에 넣을 키워드를 뽑아봤어요!</strong><br> 
        {% for i in key_list %} 
        <strong style="color:blue;">"{{i}}" </strong>
        {% endfor %}
        <strong>은 어떨까요?</strong>
    </div>
    <div class=row-2 id=row-2>
        
        <div class="thumb1">
            <img src={{img_file}}>
        </div>
        
    </div>
</div>

 
<div class="foot">
    <div class="footleft">
        <h1>
            <strong>DOBBYEDIT</strong>
        </h1>
    </div>
    <div class="footright">
        <div class='copyright'>
            <h4>
                <strong>Contact webmaster for more information. 010-지기지기-기용기용</strong>
            </h4>
        </div>
        <button class="footbtn1" onclick="location.href='{%url 'main:main' %}'">
        </button>
        <button class="footbtn2" onclick="location.href='{%url 'main:main' %}'">
        </button>
    </div>
</div>
 
</body>