board/urls.py
from django.urls import path
from . import views

app_name = 'board'

urlpatterns = [
    # 글목록
    path('postlist/', views.postlist, name='postlist'),
     
    # 글 페이지
    path('post/<int:post_no>/', views.post, name='post'),
    
    
    # 글 crud
   
    path('post/write/', views.write, name='write'),
    path('post/post/', views.post, name='post'),
    path('post/<int:post_no>/update/',views.update, name="post_update"),
    path('post/<int:post_no>/delete/',views.delete, name="post_delete"),
    # path('post/<int:post_no>/download/',views.download, name="post_file_download"),
    
    # 댓글
    path('post/<int:post_no>/comment_write/',views.comment_write, name="comment_write"),
    # path('post/<int:post_no>/comment_delete/<int:comment_no>',views.comment_delete, name="comment_delete"),
    
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from config import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('main.urls')),
    path('dobby/', include('dobby.urls')),
    path('board/', include('board.urls')),
]+ static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

dobby/urls.py
from django.urls import path
from . import views

app_name = 'dobby'

urlpatterns = [
    path('edit/', views.edit, name='edit'),      
    path('result/', views.result, name='result'),
    path('result_thumb/', views.result_thumb, name='result_thumb'), 
    path('title_select/', views.title_select, name='title_select'),     
    path('fun/', views.fun, name='fun'),
    path('result/download/', views.download, name='dobbydown'),
    # path('')    
]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('main/', views.main, name='main'),    
    path('signup/', views.signup, name='signup'),    
    path('login/', views.login, name='login'),    
    path('logout/', views.logout, name='logout'),  
    path('my/', views.my, name='my'),   
    # path('activate/<str:uidb64>/<str:token>', views.Activate.as_view(), name='status'), 
]

board/models.py
from django.db import models

from main.models import Member

# Create your models here.
class Post(models.Model):
    post_no= models.IntegerField(primary_key = True)  
    member_id = models.ForeignKey(Member, on_delete=models.CASCADE, db_column='member_id')
    post_title = models.CharField(max_length=50)
    post_detail = models.CharField(max_length=1000)
    post_update = models.DateField()

    class Meta:
        db_table = 'post'
        app_label = 'board'
        unique_together = (('post_no', 'member_id'),)
        managed = False
        


class Comment(models.Model):
    comment_no = models.IntegerField(primary_key= True)
    member_id = models.ForeignKey(Member, on_delete=models.CASCADE, db_column='member_id')
    post_no = models.ForeignKey(Post, on_delete=models.CASCADE, db_column='post_no')
    comment_detail = models.CharField(max_length=1000)
    comment_update = models.DateField()
    
    class Meta:
        db_table = 'comment'
        app_label = 'board'
        unique_together = (('comment_no', 'member_id', 'post_no'),)
        managed = False
    
    
    
class Postfile(models.Model):
    postfile_no = models.IntegerField(primary_key= True)
    post_no = models.ForeignKey(Post, on_delete=models.CASCADE, db_column='post_no')
    member_id = models.ForeignKey(Member, on_delete=models.CASCADE, db_column='member_id')
    postfile_name = models.CharField(max_length=50)
    postfile_root = models.CharField(max_length=1000)
    
    class Meta:
        db_table = 'postfile'
        app_label = 'board'
        unique_together = (('postfile_no', 'post_no', 'member_id'),)
        managed = False

board/views.py
import datetime
import json
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import redirect, render
from .models import Post, Member, Comment, Postfile

# Create your views here.
def postlist(request):
    s_id = request.session.get('s_id') # session id 유무 체크
    if s_id==None:
        return redirect("/main/login/")

    page = request.GET.get('page', '1')
    search_keyword = request.GET.get('keyword', '')
    search_type = request.GET.get('type', '')
    post_list = Post.objects.all()
    
    if search_type == 'all':
        post_list = post_list.filter(Q(post_title__icontains=search_keyword) |
                                    Q(post_detail__icontains=search_keyword) |
                                    Q(member_id__member_id__icontains=search_keyword)
                                    )
    elif search_type == 'post_title':
        post_list = post_list.filter(post_title__icontains=search_keyword)    
    elif search_type == 'post_detail':
        post_list = post_list.filter(post_detail__icontains=search_keyword)    
    elif search_type == 'member_id':
        post_list = post_list.filter(member_id__member_id__icontains=search_keyword)
    
    paginator = Paginator(post_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    print(page_obj)

    count = len(post_list)
    context = {'post_list': page_obj, 'page': page, 'keyword': search_keyword , 'count':count}
    
    return render(request, 'board/postlist.html', context)

def post(request, post_no):
    s_id = request.session.get('s_id') # session id 유무 체크
    if s_id==None:
        return redirect("/main/login/")
    
    if request.method == 'GET':
        post = Post.objects.get(post_no=post_no)
        comments = Comment.objects.filter(post_no=post_no)

        try:
            postfile = Postfile.objects.get(post_no=post_no)
            context = {
                'post':post,
                'comments':comments,
                'postfile':postfile,
            }
        except Postfile.DoesNotExist:
            context = {
                'post':post,
                'comments':comments,
            }        

        return render(request, 'board/post.html', context)
    
    
    # post메서드(댓글등록,삭제)
    else:
        comment = Comment()
        comment.post = post_no
        comment.body = request.POST['body']
        comment.date = datetime.now()
        comment.save()
        return render(request, 'board/post.html', 
                      {'post':post})


##########################################################
# def download(request, post_no):
#     if request.method == 'POST':
#         fn = request.POST["filename"]
#         filename = Postfile.objects.filter(post_no = post_no)
#         filepath = str(settings.BASE_DIR) + ('/media/%s' % filename.file_name)
#         fn = urllib3.parse.quote(fn.encode('utf-8'))
#         with open(filepath, 'rb') as f:
#             response = HttpResponse(f, content_type='application/octet-stream')
#             response['Content-Disposition'] = 'attachment; filename*=UTF-8\'\'%s' % fn
                
#     return redirect('/board/post/'+post_no)
############################################################


def write(request):
    s_id = request.session.get('s_id') # session id 유무 체크
    if s_id==None:
        return redirect("/main/login/")
    
    
    if request.method == 'POST':
        save_post_title = request.POST.get('postname')
        save_post_detail = request.POST.get('contents')
        s_id = request.session.get('s_id')
        save_member_id = Member.objects.get(member_id=s_id)
    
        now = datetime.datetime.now()
        
        a = Post(
            post_title = save_post_title,
            post_detail = save_post_detail,
            post_update = now,
            member_id = save_member_id,
        )
        a.save()
        
        
        # 파일 저장 ----- 작업중
        # try:
        #     upload_file = request.FILES.get('up_file')
            
            
        #     # 파일이 있으면 파일저장
        #     file = Postfile(
        #             postfile_name = upload_file.name,
        #             postfile_root = "\\static\\postfiles\\" + upload_file.name,
        #             member_id = save_member_id
        #         )
        #     file.save()

        #     try:
        #         with open(STATIC_ROOT+'\\postfiles\\'+upload_file.name, 'wb') as file: 
        #             for chunk in upload_file.chunks():
        #                 file.write(chunk)
        #     except FileNotFoundError:
        #         file.delete()
            
        #     # 파일이 없으면 글 작성/수정
        # except upload_file.:
        #     return redirect('/board/postlist/')



            
        # 글이 써지면 목록으로
        return redirect('/board/postlist/')
        
    else:
        # get 메서드    
        
        return render(request, 'board/write.html')
    

def update(request, post_no):
    s_id = request.session.get('s_id') # session id 유무 체크
    if s_id==None:
        return redirect("/main/login/")
    
    post = Post.objects.get(post_no=post_no)
    #
    # postfile = Postfile.objects.filter(post_no = post_no)
    #
    if request.method == "POST":
        post.post_title = request.POST['postname']
        post.post_detail = request.POST['contents']
        # post.post_update = datetime.now()
        try:
            post.file = request.FILES['image']
        except:
            post.file = None
        post.save()
        return redirect('/board/post/'+str(post.post_no),{'post':post})
    else:
        post=Post.objects.get(post_no = post_no)
        return render(request, 'board/write.html', {'post':post})




def delete(request, post_no):
    s_id = request.session.get('s_id') # session id 유무 체크
    if s_id==None:
        return redirect("/main/login/")
    
    post = Post.objects.get(post_no=post_no)
    post.delete()
    return redirect("/board/postlist/")







def comment_write(request, post_no):
    s_id = request.session.get('s_id') # session id 유무 체크
    if s_id==None:
        return redirect("/main/login/")
    
    if request.method == 'POST':
        now = datetime.datetime.now()
        s_id = request.session.get('s_id')
        jsonObject = json.loads(request.body)
        # t_post_no = jsonObject.get('post_no')
        reply = Comment.objects.create(
            # 
            post_no=Post.objects.get(post_no=post_no),
            member_id=Member.objects.get(member_id=s_id),
            comment_detail=jsonObject.get('comment_detail'),
            comment_update = now
        )
        reply.save()
        
        membername = Member.objects.get(member_id = s_id)
        context = {
            # 'name': serializers.serialize("json", reply.member_no),
            'content': reply.comment_detail,
            'pp': membername.member_nick    
        }

        return JsonResponse(context)


# def comment_delete(request):
#     comment = Comment.objects.get(comment_no=comment_no)
#     post.delete()
#     return


def file():
    
    return 

board/templates/board/post.html
{% load static %}
{% comment %} <link rel="stylesheet" href="{% static 'css/topnavi.css' %}"> {% endcomment %}
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Post</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/post.css' %}">
    <link rel="stylesheet" href="{% static 'css/topnavi.css' %}">
    {% comment %} <script src="/static/javascript/post.js"></script> {% endcomment %}
    <script
        src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js?autoload=true&skin=sunburst&lang=css">
    </script>
</head>

<body>
        {% comment %} {% if request.session.member_name %}
        <div class="navright" style="float:right;width:33%">
            <div style="float:left;width:80%">
                <a class=navright>{{ request.session.member_name }} 님 반갑습니다.</a>
            </div>
            <div style="float:right;width:20%">
                <a class=navright href="{%url 'member:logout' %}">로그아웃</a>
            </div>
        </div>
        {% else %}
        <div class="navright" style="float:right;width:33%">
            <div style="float:left;width:80%">
                <a class=navright href="{%url 'member:login' %}">로그인</a>
            </div>
            <div style="float:right;width:20%">
                <a class=navright href="{%url 'member:signup' %}">회원가입</a>
            </div>
        </div>
        {% endif %} {% endcomment %}
    <div class="nv">
        <div class="navleft">
            <h1>
                <a href="{%url 'main:main' %}">DOBBYEDIT</a>
            </h1>
        </div>
        {% comment %} <div class="navcenter"></div> {% endcomment %}
        <div class="navright">
            <div class="gnb">
                <a href="{%url 'main:main' %}" data-link="Home"></a>
                <a href="{%url 'dobby:edit' %}" data-link="영상편집"></a>
                <a href="{%url 'board:postlist' %}" data-link="커뮤니티"></a>
        </div>
        </div>
    </div>    
    <div class="container">
        <div class="comback">
        </div>
        <div class="post-group">
            <div class="post-info">
                <div class="user-icon-div">
                    <img class="user-icon" src="/static/assets/harryicon.png" alt="user icon">
                    <strong>{{ post.post_title }}</strong>
                </div>
                <div class="post-btn">
                    {% if request.session.s_id == post.member_id.member_id %}
                    <button class="adj-btn" onclick="location.href='{%url 'board:post_update' post.post_no %}'">수정</button>
                    <button class="del-btn" onclick="location.href='{%url 'board:post_delete' post.post_no %}'">삭제</button>
                    {% endif %}
                </div>
            </div>
            <div class="post">
                {% if postfile %}
                {% comment %} <form action="{% url 'board:post_file_download' post.post_no %}" method="post"> {% endcomment %}
                    <i>{{postfile.postfile_name}}</i>
                    
                    



                    {% csrf_token %}
                    <button type="submit" name="filename" value="{{ postfile.postfile_name }}">
                        다운로드
                    </button>
                </form>

                <br>
                <br>
                {{post.post_detail}}
                {% else %}
                <img src='/static/assets/post.jpg' style="width: 700px; min-width: 140px;">
                <br>
                <br>
                {{post.post_detail}}
                {% endif %}
            </div>
            <ul class="comments">
                {% comment %} {% for item in comment%}
                <li class="comment-item">
                    <div class="comment-head" id="{{item.comment_no}}">
                        <img class="user-icon" src="{% static 'assets/harryicon.jpg'%}" alt="user icon">
                    </div>

                    <div class="comment-body">
                        <p class="comment-text">{{item.comment_detail}}</p>
                        <h6>{{item.member_nick}}</h6>
                    </div>
                </li>
                {% endfor %} {% endcomment %}
                {% for com in comments%}
                <li class="comment-item">
                    <div class="comment-head" id="{{com.member_id.member_nick}}">
                        <img class="user-icon" src="/static/assets/harryicon.png" alt="user icon">
                    </div>

                    <div class="comment-body">
                        <h6>{{com.member_id.member_nick}}</h6>
                        <p class="comment-text">{{com.comment_detail}}</p>
                    </div>
                </li>
                {% endfor %}
            </ul>
            <ul>
                <li class="commemt-line">
                    <div class="comment-form">
                        <input type="text" class="comment-write" placeholder="댓글을 입력하세요">

                        <input type="submit" class="register-btn" value="등록">
                    </div>
                </li>
            </ul>
        </div>
        
    </div>
    <div class="foot">
        <div class="footleft">
            <h1>
                <strong>DOBBYEDIT</strong>
            </h1>
        </div>
        <div class="footright">
            <div class='copyright'>
                <h4>
                    <strong>Contact webmaster for more information. 010-지기지기-기용기용</strong>
                </h4>
            </div>
            <button class="footbtn1" onclick="location.href='{%url 'main:main' %}'">
            </button>
            <button class="footbtn2" onclick="location.href='{%url 'main:main' %}'">
            </button>
        </div>
    </div>
</body>
<script src="/static/javascript/post.js"></script>

<script>
    let btnUpdate = document.querySelector('.btnUpdate');
    let btnReply = document.querySelector('.register-btn');

    [...document.querySelectorAll('.register-btn')].forEach(function (item) {
        item.addEventListener('click', e => {
            let content = document.querySelector('.comment-write').value;
            //let id_check = $('.comment-head').attr('id');
            //console.log(id_check);
            console.log(content);
            document.querySelector('.comment-write').value = '';
            let param = {
                //"post_no": id_check,
                "comment_detail": content,
            }
            $.ajax({
                url: '{% url 'board:comment_write' post.post_no %}',
                type: 'POST',
                headers: {
                    'X-CSRFTOKEN': '{{ csrf_token }}'
                },
                data: JSON.stringify(param),

                //통신 받기
                success: function (receive) {
                    console.log(receive);
                    let replyTable = document.querySelector('.comments');
                    let newTr = document.createElement('li');
                    newTr.className = 'comment-item';
                    let str = `
                    <div class="comment-head">
                    <img class="user-icon" src="{% static 'assets/harryicon.png'%}" alt="user icon">
                    </div>
                    <div class="comment-body">
                        <h6>${receive.pp}</h6>
                        <p class="comment-text">${content}</p>
                    </div>`;
                    newTr.innerHTML = str;
                    replyTable.append(newTr);
                },
                error: function (request, status, error) {
                    alert("code" + request.status + '\n' + "messsage:" + request.responseText + "\n" + "error:" + error);
                }
            })
        });
    });

</script>

</html>

board/templates/board/postlist.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
{% comment %} <link rel="stylesheet" href="{% static 'css/main.css' %}"> {% endcomment %}
<link rel="stylesheet" href="{% static 'css/topnavi.css' %}">
<link rel="stylesheet" href="{% static 'css/postlist.css' %}">

<body>
    <div class='maindobby'>
        <div class="nv">
            <div class="navleft">
                <h1>
                    <a href="{%url 'main:main' %}"><img src="/static/assets/final_logo.png"style="width:100px; height:100px;"></a>
                </h1>
            </div>
            <div class="gnb">
                    <a href="{%url 'main:main' %}" data-link="Home"></a>
                    <a href="{%url 'dobby:edit' %}" data-link="영상편집"></a>
                    <a href="{%url 'board:postlist' %}" data-link="커뮤니티"></a>
            </div>
        </div>
        <div class="title">
            <h1>
                <strong>커뮤니티</strong>
            </h1>
        </div>
    </div>
{% comment %} {% for post in post_list %}
    
    <a href="{% url 'board:post' post.post_no %}">{{ post.post_title }}</a><br>

{% endfor %} {% endcomment %}
 
 
<div class="container my-3" style="color:black;">
    <div>
        {% comment %} <strong>게시판</strong> {% endcomment %}
    </div>
    <form class="row g-3" method="get" action="{% url 'board:postlist' %}" id="searchForm">
        <input type="hidden" id="type" name="type" value="{{type|default_if_none:'all'}}">
        <input type="hidden" id="keyword" name="keyword" value="{{keyword|default_if_none:''}}">
        <input type="hidden" id="page" name="page" value="{{page}}">
        <p>총 {{count}}건의 게시글이 있습니다.</p>
 
         <select class="form-select" aria-label="Default select example" id="search_type" value="{{type|default_if_none:'all'}}">
            <option value="all">전체</option> 
            <option value="post_title">제목</option>
            <option value="post_detail">내용</option>
            <option value="member_id">작성자</option>
          </select>
        <div class="col-auto">
          <input type="text" class="form-control" id="search" placeholder="검색입력" value="{{keyword|default_if_none:''}}">
        </div>
        <div class="col-auto">
          <button type="button" class="btn btn-secondary" style="background-color: rgb(110, 80, 41);" id="btn_search">검색</button>
        </div>
    </form>
    {% block script %}
    <script type='text/javascript'>
    const page_elements = document.getElementsByClassName("page-link");
    Array.from(page_elements).forEach(function(element) {
        element.addEventListener('click', function() {
            document.getElementById('page').value = this.dataset.page;
            document.getElementById('searchForm').submit();
        });
    });
    const btn_search = document.getElementById("btn_search");
    btn_search.addEventListener('click', function() {
        document.getElementById('type').value = document.getElementById('search_type').value;
        document.getElementById('keyword').value = document.getElementById('search').value;
        document.getElementById('page').value = 1;  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
        document.getElementById('searchForm').submit();
    });
    </script>
    {% endblock %}
 
    <table class="table" >
        <thead>
            <tr class="thead-dark">
                <th width="10%">번호</th><th width="15%">작성자</th><th width="50%" class="post_title">제목</th><th width="20%">작성일시</th>
            </tr>
        </thead>
        <tbody>
        {% if post_list %} <!-- 수정필요 -->
            {% for post in post_list %}
            <tr onclick="location.href='{% url 'board:post' post.post_no %}'">
                <td>{{ post.post_no }}</td>
                <td>{{ post.member_id.member_id }}</td>
                <td>{{ post.post_title }}</a></td>
                <td>{{ post.post_update }}</td>
                <td style="display:none;" >{{ post.post_detail }}</td>
            </tr>
            {% endfor %}
        {% else %}
        <tr><td colspan="3">게시물이 없습니다.</td></tr>
        {% endif %}
        </tbody>
    </table>
    <div class="col-auto">
        <button type="submit" class="btn btn-secondary" onclick="location.href='{%url 'board:write' %}'"
        style="background-color: rgb(110, 80, 41);border-color: rgb(110, 80, 41);">글쓰기</button>
    </div>
    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if post_list.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ post_list.previous_page_number }}"><<</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#"><<</a>
            
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in post_list.paginator.page_range %}
        {% if page_number >= post_list.number|add:-5 and page_number <= post_list.number|add:5 %}
        {% if page_number == post_list.number %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
        </li>
        {% endif %}
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if post_list.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ post_list.next_page_number }}">>></a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">>></a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
  
    
 
 
</div>
<div class="foot">
    <div class="footleft">
        <h1>
            <strong>DOBBYEDIT</strong>
        </h1>
    </div>
    <div class="footright">
        <div class='copyright'>
            <h4>
                <strong>Contact webmaster for more information. 010-지기지기-기용기용</strong>
            </h4>
        </div>
        <button class="footbtn1" onclick="location.href='{%url 'main:main' %}'">
        </button>
        <button class="footbtn2" onclick="location.href='{%url 'main:main' %}'">
        </button>
    </div>
</div>
 
</body>

board/templates/board/write.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'css/main.css' %}">
<link rel="stylesheet" href="{% static 'css/topnavi.css' %}">
 
 
<body>
   
<style>
input{
    width:700px;
    box-sizing: border-box;
}
input[type="text"]{
    border: solid 3px rgb(110, 80, 41);
    border-radius: 8px;
}
input[type="file"]{
    margin-top:10px;
    margin-bottom:10px;
    font-size: 20px;
}
input[type="submit"]{
    background-color: rgb(110, 80, 41);
    border-color:rgb(110, 80, 41);
 
}
textarea{
    width:700px;
    border: solid 3px rgb(110, 80, 41);
    border-radius: 8px;
}
 
.content{
    font-size: 30px;
    padding-left: 3%;
    padding-bottom: 50px;
   
}
 
.container{
    font-size: 40px;
    color: rgb(160, 158, 155);
    text-align:center;
   
}
.row{
    float:right;
    margin:10px 10px 30px 10px;
}
.form-select{
    height:50px;
    font-size: 20px;
}
.form-control{
    height:50px;
}
.col-auto{
    height:50px;
}
button{
    height:50px;
    width:100px;
    margin:0px;
}
.foot{
    background-color: rgb(110, 80, 41);
    position: relative;
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 50px 3%;
    top: 100px;
    width: 100%;
    height: 100px;
}
 

.nv {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 5%;
    top: 0;
    width: 100%;
    height: 50px;
    z-index: 1;
}

.navleft{
    display: flex;
    justify-content: left;
}

.navright{
    display: flex;
    justify-content: right;
}


.foot h1, h4{
    text-decoration: none;
    color: white;
}
 
.footleft{
    display: flex;
    justify-content: left;
}
 
.footright{
    display: flex;
    justify-content: right;
    align-items: center;
}
 
.footbtn1{
    background-color: rgb(110, 80, 41);
    border-style: none;
    height: 5vh;
    width: 5vw;
    background-image: url("/static/assets/youtube.png");
    background-size: contain;
    background-repeat: no-repeat;
    background-position: center center;
}
 
.footbtn2{
    background-color: rgb(110, 80, 41);
    border-style: none;
    height: 5vh;
    width: 5vw;
    background-image: url("/static/assets/github.png");
    background-size: contain;
    background-repeat: no-repeat;
    background-position: center center;
}
p{
    margin:25px 300px 0px 0px;
    font-size:20px;
}
body{
   
    background-color: burlywood;
}

.maindobby{
    display: flex;
    justify-content: center;
    flex-wrap: wrap;
    width: 100%;
    height: 700px;
    background-image: url("/static/assets/write.png");
    background-size: 100% 100%;
    background-repeat: no-repeat;
    background-position: center center;
}


</style>
 
 
<div class='maindobby'>
    <div class="nv">
        <div class="navleft">
            <h1>
                <a href="{%url 'main:main' %}"><img src="/static/assets/final_logo.png"style="width:100px; height:100px;"></a>
            </h1>
        </div>
        <div class="gnb">
                <a href="{%url 'main:main' %}" data-link="Home"></a>
                <a href="{%url 'dobby:edit' %}" data-link="영상편집"></a>
                <a href="{%url 'board:postlist' %}" data-link="커뮤니티"></a>
        </div>
    </div>
</div>
 
{% comment %} <body>
    <h1>post</h1>
    <hr>
    
    
    {{ post.post_detail }} <br>
    {{ comment.comment_detail }} <br>
    {{ postfile.postfile_name }} <br>


    댓글입력창 + 수정삭제(post메서드)

</body> {% endcomment %}
 
 
 
<div class="container my-3" style="color:black;">
    <div>
        <strong>게시글쓰기</strong>
    </div>
</div>
<div class="content">
    <form method="POST">
        {% csrf_token %}
        Title<br>
        {% if post.post_no %}
        <input type="text" name="postname" value="{{post.post_title}}"><br>
        {% else %}
        <input type="text" name="postname"><br>
        {% endif%}
        
        Content<br>
        {% if post.post_no %}
        <textarea rows="50" cols="50" name="contents">{{post.post_detail}}</textarea><br>
        {% else %}
        <textarea rows="50" cols="50" name="contents"></textarea><br>
        {% endif %}

        <br>
     
        <input type="submit" class="btn btn-secondary" value="작성!">
    </form>
 
 
</div>
<div class="foot">
    <div class="footleft">
        <h1>
            <strong>DOBBYEDIT</strong>
        </h1>
    </div>
    <div class="footright">
        <div class='copyright'>
            <h4>
                <strong>Contact webmaster for more information. 010-지기지기-기용기용</strong>
            </h4>
        </div>
        <button class="footbtn1" onclick="location.href='{%url 'main:main' %}'">
        </button>
        <button class="footbtn2" onclick="location.href='{%url 'main:main' %}'">
        </button>
    </div>
</div>
 
</body>